#!/bin/sh
#
# shadowsocks start/restart/stop shadowsocks
#
# chkconfig: 2345 85 15
# description: start shadowsocks/ssserver at boot time

start(){
        ssserver -c /etc/shadowsocks.json -d start
}
stop(){
        ssserver -c /etc/shadowsocks.json -d stop
}
restart(){
        ssserver -c /etc/shadowsocks.json -d restart
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        restart
        ;;
*)
        echo "Usage: $0 {start|restart|stop}"
        exit 1
        ;;
esac